Linear Algebra in NumPy

Representation of Vectors in NumPy:

In [2]:
#vectors 
import numpy as np
from numpy import linalg 
v = np.array([1,2,3])
print(v)

[1 2 3]


Operations with Vectors:

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
#addition
print(arr1 + arr1)

#dot product
print(np.dot(arr1,arr2))

# Norm
print(np.around(np.linalg.norm(arr1)))

# there are also many other operation like add, subtract, multiply that we done as same

[2 4 6 8]
70
5.0


Cosine Similarity between 2 text embeedings:

In [ ]:
'''This is used in Document similarity, shows how similar the documents are. This is the 
application of ML'''
#cosine_similarity = A . B / ||A||*||B||
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

dot = np.dot(a,b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cosine_similarity = dot /(norm_a*norm_b)
print(cosine_similarity)

0.9649505047327671


Creating Matrix in NumPy:

In [ ]:
#same as an array in numpy
a = np.array([[1,2,3],
              [5,6,7]])
print(a)
print(a.shape)

b = np.array([[7,8,9],
              [10,11,12]])
#also this have many arithmatic operations of matrices. 
print(a+b)
print(a-b)
print(a*b)
#scalar multiplication 
print(3*a)

[[1 2 3]
 [5 6 7]]
(2, 3)
[[ 8 10 12]
 [15 17 19]]
[[-6 -6 -6]
 [-5 -5 -5]]
[[ 7 16 27]
 [50 66 84]]
[[ 3  6  9]
 [15 18 21]]


Matrix Multiplication:

In [38]:
a = np.array([[1,2,3],
              [5,6,7]])
b = np.array([[7,10],[8,11],[9,12]
              ])
#2 ways to do matrix multiplication:
print(a @ b)
print(np.matmul(a,b))


[[ 50  68]
 [146 200]]
[[ 50  68]
 [146 200]]


Matrix Transpose:

In [36]:
a = np.array([[1,2,3],
              [5,6,7]])
print(a.T)
print(np.linalg.matrix_transpose(a))
print(np.transpose(a))
#the interchange of columns to rows and rows to columns

[[1 5]
 [2 6]
 [3 7]]
[[1 5]
 [2 6]
 [3 7]]
[[1 5]
 [2 6]
 [3 7]]


Types of Matrices:

In [ ]:
#square matrix
print(np.array([[1,2],[1,2]]))
#zero matrix
z = np.zeros((2,3))
print(z)
#identity matrix
i = np.eye(3)
print(i)
#diagnal matrix
d = np.diag([1,2,3])
print(d)
#scalar matrix
k = 5
s = np.diag([k]*3)
print(s)
#symmetric matrix
s = np.array([[1,2],[2,3]])
print(s.T)
#upper triangular matrix
u = np.triu([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(u)
#lower triangular matrix
l = np.tril([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(l)


[[1 2]
 [1 2]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[5 0 0]
 [0 5 0]
 [0 0 5]]
[[1 2]
 [2 3]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


Products of vectors and matrices in NumPy:

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.inner(a,b))  #1*2+2*5+3*6

print(np.outer(a,b))  #where each element is the product of elements from both vectors

print(np.cross(a,b))

#vdot:
# Simple vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vdot(a, b))   # 32
#product of complex numbers:
# Python Program illustrating
# numpy.vdot() method

# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j

product = np.vdot(vector_a, vector_b)
print("Dot Product  : ", product)



32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]
32
Dot Product  :  (23-2j)


Determinant of a matrix:

In [ ]:
a = np.array([[1,2],[3,4]])
res = np.linalg.det(a)
print(res)

#use of np.linalg.slogdet
sign , logdet = np.linalg.slogdet(a)
result = sign * np.exp(logdet) 
''' First the determinant of the value. then the sign of the determinant. then the natural log of 
determinant and then res=sign * e^logdet = det(A)'''
print(result)

-2.0000000000000004
-2.0000000000000004


Inverse of a Matrix:

In [4]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))
"""
if det(A)!=0:
    A_inv=adj(A)/det(A)
else:
    print("not Exist")
    """
print("--------------------------------")
import numpy as np
A = np.array([[[1., 2.],[3., 4.]],
              [[1, 3], [3, 5]]])
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
--------------------------------
[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]


Eigenvalues or Eigenvectors:

In [7]:
import numpy as np

A = np.array([[4, -2],
              [1,  1]])

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors (columns):")
print(eigenvectors)


Eigenvalues:
[3. 2.]

Eigenvectors (columns):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
