What is ufunc?

ufunc stands for "Universal Functions" and they are NumPy functions that operate on ndarray



Why use ufunc?

. They are used to immplement vectorization which is a way faster than iterating over the elements
. They also provide provide broadcasting and additional methods like reduce and accumulate etc. and they 
  are very helpful for computation


Arguments:

ufuncs also take additional arguments, like:
(where) boolean array or condition defining where the operations should take place.
(dtype) defining the return type of elements.
(out) output array where the return value should be copied.



What is Vectorization?

Vectorization means performing an operation on the entire array at once, instead of looping through the elements one by one

Without ufunc the code runs as:

In [ ]:
x = [1,2,3,4,5]
y = [1,2,3,4,5]
z = []
for i , j in zip(x,y):
    z.append(i+j)
print(z)


[2, 4, 6, 8, 10]


With ufunc, we can simply add those using np

In [2]:
import numpy as np

x = [1,2,3,4,5]
y = [1,2,3,4,5]
z = np.add(x,y)
print(z)

[ 2  4  6  8 10]


Create your own ufunc

In [4]:
def myadd(x,y):
    return x+y
# frompyfunc can takes 3 arguments:
'''
1. function
2. Number of inputs (arrays)
3. Number of output
'''
myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[1,2,3,4]))


def custom_func(x):
    return x**2 + 2*x + 1

a1 = np.array([1, 2, 3, 4])
result = custom_func(a1)
print(result)

[2 4 6 8]
[ 4  9 16 25]


Checking if a function is ufunc or not:

In [6]:
print(type(np.add))

<class 'numpy.ufunc'>


In [7]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [9]:
if type(np.add) == np.ufunc:
    print("Its a universal function")
else:
    print("Its not a universal function ")

Its a universal function


Addition,Subtraction, Multiplication:

In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

x = np.add(arr1,arr2)
print(x)

x = np.subtract(arr1, arr2)
print(x)

x = np.multiply(arr1,arr2)
print(x)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]


Division, Power, Multiply:

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

x = np.divide(arr1, arr2)
print(x)

x = np.power(arr1,arr2)
print(x)

x = np.mod(arr1,arr2)  #we also use remainder()
print(x)


[ 3.33333333  4.          5.          5.         25.          1.81818182]
[         1000       3200000     729000000 6553600000000          2500
             0]
[ 1  0  0  0  0 27]


Quotient and Mod, Absolute values

In [17]:
'''The Divmod() function returns both quotient and remainder.It returns 2 arrays, 
the first array contains the quotient and the other is mod
'''
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

x = np.divmod(arr1, arr2)
print(x)

arr1 = np.array([-1,-2,-3,-4,0,1])
x = np.absolute(arr1)
print(x)


(array([ 3,  4,  5,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))
[1 2 3 4 0 1]


Rounding decimals (truncation,fix,rounding,floor,ceil)

In [25]:
arr = np.trunc([-3.3333,34.123])
print(arr)

arr = np.fix([-3.3333,34.123])
print(arr)

arr = np.around(3.1666, 2)
print(arr)

arr = np.floor([-3.3333,34.123])
print(arr)

arr = np.ceil([-3.3333,34.123])
print(arr)

[-3. 34.]
[-3. 34.]
3.17
[-4. 34.]
[-3. 35.]


NumPy Logs:

In [ ]:
#log at base 2:
arr = np.arange(1,10)
print(np.log2(arr))

# log at base 10
print(np.log10(arr))

# Natural log and log at base e
print(np.log(arr))


'''Numpy has not any function for log at any base. So, we can from maths, import log'''
from math import log

nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


NumPy Summations:

In [34]:
'''Add function accepts only 2 arguments and returns the sum over the elements of the array 
but the sum function accepts n arguments and returns the sum of all the elements of the array
'''
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
x = np.add(arr1,arr2)
print(x)

x = np.sum([arr1,arr2])
print(x)

#sum over axis 1,means the sum of arr1 and sum of arr2
x = np.sum([arr1,arr2],axis=1)
print(x)
# Cumulative sum means [1,2,3] so [1,1+2,1+2+3]
x =np.cumsum(arr1)
print(x)

[ 2  4  6  8 10]
30
[15 15]
[ 1  3  6 10 15]


NumPy Products:

In [ ]:
#products
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

x = np.prod(arr1)
print(x)

x = np.prod([arr1,arr2])
print(x)

x = np.prod([arr1,arr2],axis=1)
print(x)

x = np.cumprod(arr1)
print(x)



120
14400
[120 120]
[  1   2   6  24 120]


NumPy Differences

In [ ]:
'''E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
'''
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

newarr = np.diff(arr,n=2)
print(newarr)

[  5  10 -20]
[  5 -30]


NumPy LCM:

In [ ]:
num1 = 4
num2 = 6
x = np.lcm(num1,num2)
print(x)

# LCM over the arrays:
arr = np.array([3,6,9])
x = np.lcm.reduce(arr)
print(x)

arr = np.arange(1,10)
x = np.lcm.reduce(arr)
print(x)


12
18
2520


NumPy GCD:

In [ ]:
num1 = 12
num2 = 16
arr = np.gcd(num1,num2)
print(arr)

arr = np.array([1,2,3,4,5])
x = np.gcd.reduce(arr)
print(x)


4
1


NumPy Trignometric Functions:

In [ ]:
x = np.sin(np.pi/2)
print(x)

#find the sin() of all elements in the arrays
x = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
arr = np.sin(x)
print(arr)

#convert all values of degree to radian
x = np.array([45,60,90,120])
arr = np.deg2rad(x)
print(arr)

#convert all values of radian to degree
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

#calculating the inverse
x = np.arcsin(1.0)
print(x)

arr = np.array([1,-1,0.1])
x = np.arcsin(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]
[0.78539816 1.04719755 1.57079633 2.0943951 ]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]


Hypotenues:

In [12]:
#hypotenues also calculated in numpy using pythagoras theorem,as it takes perpendiculae and base.
base = 3
perp = 4
x = np.hypot(base, perp)
x

np.float64(5.0)

NumPy Hyperbolic Functions:

In [14]:
x = np.sinh(np.pi/2)
print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

x = np.arcsinh(1.0)
print(x)

arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]
0.881373587019543
[0.10033535 0.20273255 0.54930614]


NumPy Set Operations:

In [20]:
#Convert array of repeated elements in a set
x = np.array([1,1,2,2,4,4,5,6,7,8,8])
arr = np.unique(x)
print(x)

x = np.array([1,2,4,5,5])
x1 = np.array([2,3,4,6,8])
arr = np.union1d(x,x1)
print(arr)

arr = np.intersect1d(x,x1,assume_unique=True)
print(arr)

arr = np.setdiff1d(x,x1,assume_unique=True)
print(arr)

arr = np.setxor1d(x,x1,assume_unique=True)
print(arr)


[1 1 2 2 4 4 5 6 7 8 8]
[1 2 3 4 5 6 8]
[2 4 5]
[1 5 5]
[1 3 6 8]


Square root:

In [ ]:
x = np.sqrt(64)
print(x)
#same for array 

8.0


Exponential Values:

In [ ]:
a = np.array([0, 1, 2, 3]) #e^0,e^1,e^2
print ("Exponent of array elements:", np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
