Broadcasting:

Broadcasting in NumPy allows us to perform arithmatic operations on arrays of different shapes without reshaping it. It makes an easy way to do an element-wise operation in array and reducing and eliminating the need of loops.

In [5]:
import numpy as np
 
arr = np.array([[1,2,3,4],[1,2,3,4]])
scalar = 10
x = arr + 10
print(x)

#Broadcasting with 1D
arr = np.array([1,2,3,4,5])
x = arr + 2
print(x)

[[11 12 13 14]
 [11 12 13 14]]
[3 4 5 6 7]


Broadcasting with conditional operator:

In [6]:
age = np.array([10,20,25,15,22,30,23])
age_group = np.array(['Minor','Adult'])
result = np.where(age>18,age_group[0],age_group[1])
print(result)

['Adult' 'Minor' 'Minor' 'Adult' 'Minor' 'Minor' 'Minor']


Using Broadcasting for Array Multiplication 

In [7]:
a = np.array ([[1,2,4],[4,5,6]])
b = np.array ([2,3,4])
x = a * b
print(x)

[[ 2  6 16]
 [ 8 15 24]]
