NumPy (Numerical Python)

In [3]:
import numpy as np
import math 

# use a list to create an array 
arr = np.array([1,2,3,4,5])
print (arr)
print (type(arr))

# Use a tuples to create an array 
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


N-Dimensional Array 

In [48]:
# 0-D array 
arr0 = np.array (42)
print(0)
# to print the dimensions of this array, we use ndim built-in function 
print(arr0.ndim)

print("---------")

# 1-D array
arr1 = np.array ([1,2,4,6,4])
print(arr1)

print("---------")

#2-D array 
arr2 = np.array([[1,2,4],[5,7,8]])
print(arr2)

print("---------")

# 3-D array 
arr3 = np.array([[[1,2,3],[1,2,3],[2,3,4]]])
print(arr3)
print(arr3.ndim)

print("---------")

# for higher dimensions 
arr4 = np.array([[6,7,8,9],[1,2,3,4]],ndmin=5)
print(arr4)





0
0
---------
[1 2 4 6 4]
---------
[[1 2 4]
 [5 7 8]]
---------
[[[1 2 3]
  [1 2 3]
  [2 3 4]]]
3
---------
[[[[[6 7 8 9]
    [1 2 3 4]]]]]


Indexing in NumPy Array 

In [ ]:
# Indexing returns the element that are in position  (1D Array)
arr = np.array([1,2,3,4,5])
print(arr[0])

# get 2nd and 3rd element of an array and add them

c = arr[1] + arr [2]
print(c)

# Accessing 2D array
arr2 = np.array([[1,2,4]
                 ,[5,7,8]])
print(arr2[1,2])   #[1,2] 1 is row no. and 2 is column number. Starts from 0. so it returns 8
# more on 2D accessing
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print("1st row and 4th column: ",arr[0,3])

# Accessing 3D array 
# so explanation of this as, [0,1,2], 0 shows the dept meanig the matrix, 1 shows the row of that matrix 
#  and 2 shows the column of that matrix
arr = np.array([[[1, 2, 3],
                [4, 5, 6]],

                [[7, 8, 9],
                [10, 11, 12]],

                [[34,23,45],
                 [23,45,23]]
                ])
print(arr.ndim)
print(arr[0,1,2])
print(arr[1,1,1])
print(arr[2,1,1])

# Negative indexing 
arr45 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr45[1, -1])

1
5
8
1st row and 4th column:  4
3
6
11
45
Last element from 2nd dim:  6


Slicing in NumPy

In [ ]:
arr = np.array([1,2,3,4,5])
# [start : Stop : Step ]
# 1D array 
print(arr[0:6])
print(arr[:])
print(arr[2:])
print(arr[:4])

# Negative Slicing
print(arr[-4:-1])

# STEP 
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

# 2D array 
#  [dept,slicing:slicing]
arr2 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
print(arr2[1,0:5])
print(arr2[0:2,2])
print(arr2[0:2,1:5]) #this will return a 2D array

[1 2 3 4 5]
[1 2 3 4 5]
[3 4 5]
[1 2 3 4]
[2 3 4]
[1 3 5 7 9]
[ 6  7  8  9 10]
[3 8]
[[ 2  3  4  5]
 [ 7  8  9 10]]


Data types in Python 

In [116]:
# We have many data types in Python
arr = np.array([1,2,3,4,5])
print(arr.dtype) #int64

arr = np.array([1.2,3.5,1.0,23.5])
print(arr.dtype) #float64

arr = np.array(['a','e','i','o','u'])
print(arr.dtype) #<U1 (unicode string) with length 1

# Create an array with a defined datatype
arrof = np.array([1,2,3,45,5],dtype='S')
print(arrof)
print(arrof.dtype)

arrofi= np.array([1,2,3,45,5],dtype='i4')
print(arrofi)
print(arrofi.dtype) #int32 (4 means of 4 bytes. meaning 32 bits)

# if we want to cast a datatype character to integers, it will raise an error
# arrcast = np.array(['a','2','b'], dtype='i')
# print(arrcast)

arrtoconvert = np.array([1.1,2.2,3.4,5.6]) #float to int
newarr = arrtoconvert.astype('i')
print(newarr)

arrtoconvert = np.array([1,2,3,4,5,6])
newarr = arrtoconvert.astype('f')
print(newarr)

arrtoconvert = np.array([-1,0,1])
newarr = arrtoconvert.astype('bool')
print(newarr)




int64
float64
<U1
[b'1' b'2' b'3' b'45' b'5']
|S2
[ 1  2  3 45  5]
int32
[1 2 3 5]
[1. 2. 3. 4. 5. 6.]
[ True False  True]


Zeros and Ones

In [248]:
a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


NumPy Arrange Function 

In [253]:
#  The fist argument is thestarting bound and the second argument is the ending bound, 
# and the third argument is the difference between
# each consecutive numbers

# Let's create an array of every even number from ten (inclusive)  to fifty (exclusive)
a = np.arange (10,50,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Linespace

In [ ]:
# It means to create an array of range 2 to 3 and 15 doesn't means the differ b/w 2 and 3 
# but the total elements in the array 
p = np.linspace(2,3,15)
p

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

Some Aggregate functions

In [260]:
arr1 = np.array([6,2,4,6,8,9,1,22])
print(arr1.max())
print(arr1.sum())
print(arr1.mean())
print(arr1.min())

22
58
7.25
1


Routines Matrix:

In [17]:
#eye
identity_mat = np.eye(3)
print(identity_mat)

#diagnal matrix
diagnal_mat = np.diag([1,2,3])
print(diagnal_mat)

#zero-like
zerolike = np.zeros_like(diagnal_mat)
print(zerolike)

#one-like
onelike = np.ones_like(diagnal_mat)
print(onelike)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Copy and View Operation in Array 

In [ ]:
arrforcopy = np.array ([1,2,3,4,5])
x1 = arrforcopy.copy() #doesn't have any arguments

x1 [4] = 6
print(arrforcopy)
print(x1)

'''So the main difference b/w copy and view is that copy is a new array with 
same data, and view is just a view of the original array. 
If we do any operation on copy, it doesn't changes the original array, but on 
the other hand, if we do the changes on view, then it changes the original array 
'''
print("---------------------")
arrforview = np.array ([1,2,3,4,5])
x2 = arrforview.view() #doesn't have any arguments

x2 [4] = 6
print(x2)
print(arrforview)

# Checks if an array own its data
''' The base attribute returns none if an array owns its data
'''
print(x1.base)
print(x2.base)

[1 2 3 4 5]
[1 2 3 4 6]
---------------------
[1 2 3 4 6]
[1 2 3 4 6]
None
[1 2 3 4 6]


Array Operations 

In [256]:
# WE can do many arithematic oprations on the arrays, but here is the most important operation 
A = np.array([[1,1] ,[0,1]])
B = np.array([[2,0], [3,4]])
print(A*B)
# Note: * always do the element-wise product of a matrix
# if we want a matrix multiplication method (rows to columns) then use  @
print(A@B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


Shape of an Array 

In [170]:
arr = np.array ([1,2,3,4,5])
print(arr.shape)   #returns a tuples

arr = np.array ([[2,3,4,5],[6,7,8,9]])
print(arr.shape)   #(2,4) 2 is the number of rows and 4 is the number of columns 

arr=  np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.shape)

print()
# Reshape an array 
print("Reshaping:")
arr1 = np.array ([1,2,3,4,5,6])
print(arr1)
x = arr1.reshape(2,3) #1D to 2D 
print(x)

print()

arr3= np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr3)
x3 = arr3.reshape(2,2,3) #1D to 3D 
# checking if the reshaped array is copy or view
print(x3) #returns the array, so it is view

# then convert this 3D back to 1D 
# or 
# xone = arr3.reshape(12,) 
xone = arr3.reshape(-1) 
print(xone)



(5,)
(2, 4)
[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)

Reshaping:
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Iterating Arrays 

In [ ]:
arr1  = np.array ([1,2,3,4,5,6])
# over 1D array 
for x in arr1:
    print(x)

arr2 = np.array([[1,2,3],[4,5,6]])
for x in arr2:
    print(x) #shows row by row
print()
for x in arr2:
    for y in x: #show element by element 
        print(y)
print()
arr3 = np.array ([[[1,2,4],[5,6,7],[8,9,10]]])
for x in arr3:
    for y in x:
        for z in y:
            print(z)
# np.nditr is a function used to iterate over all dimensions in an array. 
for x in np.nditer(arr2):
    print(x)


1
2
3
4
5
6
[1 2 3]
[4 5 6]

1
2
3
4
5
6

1
2
3
4
5
6


In [ ]:
#iterating using nditer or changes the datatypes during exeution of iteration.
arr = np.array ([[1,2,3],[4,5,6]])
for x in np.nditer(arr, flags=['buffered'] , op_dtypes=['S']):
    print(x)

'''
Where does buffered come in?
You can’t just change the candy in the jar directly (that’s the array’s fixed dtype).
So, the factory makes a temporary basket 🧺 where each candy is taken out, wrapped in
 foil, and then handed to your friend.
This temporary basket = buffered flag.
'''
# Slicing in iteration 






arr = np.array ([1,2,3])
# When we want both sequence number and the value
for idx , x in np.ndenumerate(arr):
    print(f"{idx} on {x}")





np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
(0,) on 1
(1,) on 2
(2,) on 3


Joining NumPy Arrays

In [ ]:
# Join 1D array 
arr1 = np.array ([1,2,3,4,5])
arr2 = np.array ([6,7,8,9,10])
newarray = np.concatenate((arr1 ,arr2))
# axis function doesn't work in 1D array because there is nothing to join 
print(newarray)
print()
# join 2D array 
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[7,8,9],[10,11,12]])
newarray = np.concatenate((arr3,arr4),axis=0) 
print(newarray)
# So in this axis means, if 0 then add more rows. If 1 then add more columns.
print()
# joining 3D array 
arr3f = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr4f = np.array([[[13, 14, 15], [16, 17, 18]],[[19, 20, 21], [22, 23, 24]]])
newarr = np.concatenate((arr3f,arr4f), axis=2)
print(newarr)

print()

# Stack 
'''Stack is used to add axis in 1D array. concatenation doesn't accepts any axis'''
arr1 = np.array ([1,2,3,4,5])
arr2 = np.array ([6,7,8,9,10])
newarray = np.stack((arr1 ,arr2), axis=1) #if 0 then, arrays become rows, if 1 then, arrays become columns
print(newarray)
print()

# Stacking along Rows
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new = np.hstack((arr1,arr2))
print(new)
print()

# Stacking along columns
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new = np.vstack((arr1,arr2))
print(new)
print()

# Stacking along height (depth)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new = np.dstack((arr1,arr2))
print(new)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2  3 13 14 15]
  [ 4  5  6 16 17 18]]

 [[ 7  8  9 19 20 21]
  [10 11 12 22 23 24]]]

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


Splitting in Arrays

In [ ]:
''' There are 2 functions for splitting an array. 
1. split() (divide the array in equal parts)
2. array_split() (arrys equality doesn't matter)
'''
arr = np.array ([1,2,3,4,5,6,7])
newarr= np.array_split(arr, 2) #2 means divide into 2 parts(no matter these parts are equal or not)
print(newarr)
# we can also access the element from the splitted array 
print(newarr[0])
print(newarr[1])

# the same function also use for 2D arrays and 3D array 
arr = np.array([[1,2,3],[4,5,6]])
newarr = np.array_split(arr,3)
print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr,3,axis=1) #along columns
print(newarr)
print()

# another way to do along columns 
arr = np.array([[1,2,3],[4,5,6]])
neww = np.vsplit(arr , 2)
print(neww)
# same work for hsplit

[array([1, 2, 3, 4]), array([5, 6, 7])]
[1 2 3 4]
[5 6 7]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[1, 2, 3]]), array([[4, 5, 6]])]


Searching in NumPy 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
n = np.where(arr == 4)
print(n) #returns the index number in a tuples in an array 

even = np.where(arr%2==0)
print(even)  #returns the index in a tuple where the even number is present 

odd = np.where(arr%2==1)
print(odd)

sorted_array = np.array([2,5,8,9,16,20])
index = np.searchsorted(sorted_array,4)
print(index)   
'''Search sorted function assumes that our array is already sorted.
and it simply insert the number we given to this and returns the index number in which the 
number is inserted
 '''
s = np.array([2,5,8,9,16,19,20])
index = np.searchsorted(s,19, side='left')
print(index)

# Multiple values 
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)



(array([3]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6, 8]),)
1
5
[1 2 3]


Sorting in Arrays 

In [238]:
arr = np.array([3,7,4,6,2,1,6,4,2,9])
newww = np.sort(arr)
print(newww)

arr = np.array([[6,4,2],[9,2,5]])
new = np.sort(arr)
print(new)

arr = np.array([False, True, False])
newww = np.sort(arr)
print(newww)


[1 2 2 3 4 4 6 6 7 9]
[[2 4 6]
 [2 5 9]]
[False False  True]


Filtering in NumPy 

In [245]:
arr = np.array([41,42,43,44])
b = [True, False ,True, True]
newarr = arr[b]
print(newarr)

# making of filter Array 
# make an empty list
filter_arr =[]
for x in arr:
    if x>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newfilter = arr[filter_arr]
print(filter_arr)
print(newfilter)

# More on Filtering of an array 
# lets do one more example:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
filter_even = []
for x in arr:
    if x%2==0:
        filter_even.append(True)
    else:
        filter_even.append(False)

new =arr[filter_even]
print(new)

# create filter directly from the array (like Short hand if_else)
filterd = arr%2==0
n=arr[filterd]
print(n)


[41 43 44]
[False, False, True, True]
[43 44]
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]


Working with Random library in NumPy

In [5]:
from numpy import random
arr = random.rand(4)
print(arr) #return a 4 random float numbers

x = random.rand(2,3)
print(x) #return a 2D array 

# generate random number from the array 
x =random.choice([2,3,4,5,6])
print(x)

x = random.choice([3,4,5,6,7,8], size=(3,5))
print(x) #size is the size of an array with 3 rows and 5 columns

# Random data distribution 
x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(100))
print(x) #SUM of all probabilities must be equals to one

x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(2,3))
print(x) #RETURNS a 2D array




[0.80636639 0.18096764 0.56776149 0.11920034]
[[0.13286023 0.17609362 0.78329332]
 [0.15606337 0.5577349  0.41443682]]
6
[[8 7 7 3 8]
 [4 4 3 3 3]
 [5 3 4 4 3]]
[7 7 5 5 7 3 7 5 5 5 5 7 7 5 7 7 5 5 7 5 5 7 7 7 7 5 7 5 7 5 7 7 7 7 3 7 7
 7 7 5 7 5 5 7 7 7 7 5 7 3 7 5 3 5 7 7 5 7 7 7 3 7 7 3 5 7 7 5 7 5 7 3 7 7
 7 7 7 7 3 5 5 7 5 5 7 7 7 7 7 7 7 7 7 7 3 7 7 5 7 7]
[[7 5 7]
 [7 5 5]]


Permutation 

In [6]:
'''So there are 2 functions of random permutation. 
1. Shuffle (to make changes in the orignal array )
2. Permuation (to make changes in the new array and leaves the original array un-changed)
'''
arr = np.array([1,2,3,4,5,6,7])
random.shuffle(arr)
print(arr)

arr = np.array([1,2,3,4,5,6])
x= random.permutation(arr)
print(x)    #the new array forms
print(arr) #the original array is as it is. 



[5 4 3 7 6 1 2]
[4 1 2 3 6 5]
[1 2 3 4 5 6]


fromiter functions:

In [11]:
a = "python"
x = np.fromiter(a, dtype='U2')
print(x)

iterable =( x * x for x in range(6))
func = np.fromiter(iterable,float)
print(func)

['p' 'y' 't' 'h' 'o' 'n']
[ 0.  1.  4.  9. 16. 25.]


Empty Functions:

In [12]:
# Create an empty array of shape (3, 2) with integer data type
empty_ = np.empty((3, 2), dtype=int)
print("Empty integer array:\n", empty_)


Empty integer array:
 [[                  0 4607182418800017408]
 [4616189618054758400 4621256167635550208]
 [4625196817309499392 4627730092099895296]]
